### ISSUE TITLE
Plugin does not seem to respect hist_* options

### ISSUE THREAD

**Issue by GoNZooo** [jimhester/per-directory-history#14]
As an example: 'setopt hist_ignore_space' does not apply when using this plugin, it would seem.

I have tried setting hist options before and after loading the plugin, but it doesn't seem to make a difference.

My plugins are: `plugins=(gitfast last-working-dir vi-mode ssh-agent per-directory-history)` on zsh version 5.0.8.

**Comment by akiross** [comment]
I have the same issue, especially with `hist_ignore_space` which appears to be ignored.

**Comment by Idlusen** [comment]
I think the problem lies in the `_per-directory-history-addhistory` function.
I’m not sure why it doesn’t observe `hist_ignore_space`, but as a simple workaround prepending the function with `if [[ -o hist_ignore_space && "$1" =~ "^ " ]]; then return; fi` seems to work.

**Comment by jimhester** [comment]
Should be fixed by https://github.com/jimhester/per-directory-history/pull/26
