### ISSUE TITLE
FLOSS license?

### ISSUE THREAD

**Issue by mschilli87** [jimhester/per-directory-history#18]
Hi @jimhester,

Thank you for implementing this nice feature.
Is there any chance you plan to release this code under an FSF approved (standard) license?
This would make it much easier to (optionally) bundle this with ZFS when packaging for distributions.

Best regards,
Marcel

**Comment by jimhester** [comment]
This project is already licensed with the [Zlib License](https://en.wikipedia.org/wiki/Zlib_License), which is a FWF approved license.

**Comment by jimhester** [comment]
I tweaked the license format slightly, and GitHub now auto-detects it properly.
