### ISSUE TITLE
Toggle message is chopped if current line is being edited

### ISSUE THREAD

**Issue by jimhester** [jimhester/per-directory-history#2]
This seems to be a bug in zsh rather than this plugin, but I would need to do more research to figure out if there is a workaround.

To produce type some text, then toggle the history, the toggle message will be chopped by some random amount, happens with both multi-line and single line prompts.

**Comment by CyberShadow** [comment]
Clearing the line first worked for me: https://github.com/CyberShadow/per-directory-history/commit/7cde5cde6f5813ce5f364d6699cec3dd39c471c6
