### ISSUE TITLE
Commands entered in directory history are not added to global history

### ISSUE THREAD

**Issue by IgnusG** [jimhester/per-directory-history#21]
It seems the commands executed in global history mode are also saved to the directory history.
But commands executed in the directory history mode are not added to the global one. 

Is this intended?

**Comment by kadaan** [comment]
This just started happening to me too.  Pretty sure it worked before.

**Comment by p-patil** [comment]
I'm also seeing this issue.

**Comment by deathtrip** [comment]
Is this still happening with new zsh versions?
I wanna try the plugin, but i'm not sure if it will work properly.

**Comment by open-dynaMIX** [comment]
I've just started playing around with this nice plugin. It seems that `incappendhistory` is not respected. As soon as I close the shell, the entries are written to the global history file.

**Comment by CyberShadow** [comment]
Due to this problem I switched to a different implementation of this plugin in my fork:
https://github.com/CyberShadow/per-directory-history/commit/b8e7a9644f5c89562a08e36eede577e8a8081eca

This version works with `share_history` for me in current ZSH.
