### ISSUE TITLE
can't view the global history

### ISSUE THREAD

**Issue by nawtrobar** [jimhester/per-directory-history#22]
I can only view the history of the current directory and the toggle key does not appear to work. I peaked at the zsh script and found that the command line should print "using local history" / "using global history" when I press ^G. However, it does not. I'm unsure if any of the other plugins I've installed interfere with this.

**Comment by npreiber** [comment]
Resolved vi-mode was installed and interfering, loading vi-mode before per-directory-history seems to resolve the problem.
