### ISSUE TITLE
I moved a directory, can I import the history from the directories old location ?

### ISSUE THREAD

**Issue by stuaxo** [jimhester/per-directory-history#24]
I moved a directory and can't access its per-directory history any more, is there a way I can import the history from its old location ?

Once this exists, it would be great if there was a way to enable this automatically for mv (and maybe cp).

**Comment by jimhester** [comment]
Sure, just move the corresponding history entry, e.g. the file `~/.directory_history/$(pwd -P)/history` (corresponding to the old location) to the new one.

**Comment by cohml** [comment]
Could probably close this issue, JFYI.
