### ISSUE TITLE
Configurable default initial mode

### ISSUE THREAD

**Issue by mmenozzi** [jimhester/per-directory-history#3]
Hi,
I'm not an expert of zsh. It is possible to configure in any way which is the default inital mode? I noticed that, on my shell, with this plugin enabled (I'm using oh-my-zsh) the shell starts using local history mode by default. I want to change this behavior and start my shell using global history mode by default. Is it possible?

Thank you.

**Comment by xuhdev** [comment]
Can you add this info to README, please? I believe a lot of people are looking for it.
